apiVersion: apps/v1
kind: Deployment
metadata:
  name: isvaop
  labels:
    app: isvaop
  annotations:
    version: "2.0"
spec:
  selector:
    matchLabels:
      app: isvaop
  replicas: 1
  template: 
    metadata:
      labels:
        app: isvaop
    spec:
      # The name of the service account which has the required capabilities enabled for the ISVAOP container.
      serviceAccountName: isvaop
      volumes:        
        - name: isvaconfig-aac
          configMap:
            name: isvaop-config
        - name: certs
          secret:
            defaultMode: 420
            secretName: aws-rds-ca-files
      containers:
        - name: isvaop    
          # The fully qualified name of the ISVAOP image.
          image: icr.io/isva/verify-access-oidc-provider:24.06
          imagePullPolicy: Always
          # Mount our volumes to the expected configuration directory
          volumeMounts:
            - name: isvaconfig-aac
              mountPath: /var/isvaop/config
            - name: certs
              mountPath: /etc/pki/ca-trust/source/aws-rds.crt
              readOnly: true
              subPath: aws-rds.crt
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: 8436
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthcheck/alive
              port: 8436
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: isvaop
  labels:
    app: isvaop
spec:
  ports:
    - port: 8436
      name: isvaop
      nodePort: 31443
  selector:
    app: isvaop
  type: NodePort