keystore:
  - name: server_keys
    type: pem
    certificate:
      - label: server_cert
        content: "secret:isvaop-keystores/server_cert.pem"

    key:
      - label: server_key
        content: "secret:isvaop-keystores/server_key.pem"
  - name: isvaop_signing
    type: pem
    key:
      - label: rsakey
        content: "secret:isvaop-keystores/rsakey.pem"

