# Copyright contributors to the IBM Security Verify Access OIDC Provider Resources project
runtime_db: redis-standalone                    # Configuration of runtime database. Points to the database server connection
session_cache:
  type: redis                       # Specifies the type of session cache, in-memory, redis, or db.
  cfg: redis-standalone             # Specifies the configuration of the `redis` cache, for `redis` type only. Points to `redis` server connection                                    
server_connections:
  - name: redis-standalone          # Connection name
    type: redis                     # Connection type
    deployment:                     # Redis deployment information. for `redis` type only
      model: standalone             # Deployment model. standalone or sentinel
    hosts:                          # List of host information (IP and port).
      - hostname: ciam-elastic-redis.svam.nonprod.pvcombank.io      # Server's hostname.
        hostport: 6379              # Server's host port.
    credential:                     # Credential information to connect to the server.
      #username: root               # Specifies the username to access the server.
      password: 3ZV5JPAheVT6EXV7gRjg!      # Specifies the password to access the server. It is recommended to obfuscate this.
    ssl:
      certificate:
        - 'secret:isvaop-keystores/postgres-rdc.pem'
      disable_hostname_verification: true
